### ISSUE TITLE
[IntegTest][Bug] async-search failed on no-security integ-test on 2.2.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/asynchronous-search#168]
```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.search.asynchronous.integTests.AsynchronousSearchStatsIT.testStatsAcrossNodes" -Dtests.seed=915C684E4885D9F1 -Dtests.security.manager=false -Dtests.locale=is-IS -Dtests.timezone=Kwajalein -Druntime.java=17


Suite: Test class org.opensearch.search.asynchronous.integTests.AsynchronousSearchStatsIT
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.search.asynchronous.integTests.AsynchronousSearchStatsIT.testStatsAcrossNodes" -Dtests.seed=915C684E4885D9F1 -Dtests.security.manager=false -Dtests.locale=is-IS -Dtests.timezone=Kwajalein -Druntime.java=17
  2> java.lang.AssertionError: expected:<20> but was:<19>
        at __randomizedtesting.SeedInfo.seed([915C684E4885D9F1:AFB99D223D9590BC]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.search.asynchronous.integTests.AsynchronousSearchStatsIT.testStatsAcrossNodes(AsynchronousSearchStatsIT.java:188)
  2> NOTE: leaving temporary files on disk at: /tmp/tmp4wx1o2at/asynchronous-search/build/testrun/integTest/temp/org.opensearch.search.asynchronous.integTests.AsynchronousSearchStatsIT_915C684E4885D9F1-001
  2> NOTE: test params are: codec=Asserting(Lucene92): {_routing=Lucene90, field1.keyword=PostingsFormat(name=Asserting), index_uuid=Lucene90, field1=PostingsFormat(name=Asserting), _field_names=Lucene90, _id=Lucene90, type=Lucene90}, docValues:{field1.keyword=DocValuesFormat(name=Asserting), __soft_deletes=DocValuesFormat(name=Lucene90), _seq_no=DocValuesFormat(name=Lucene90), _tombstone=DocValuesFormat(name=Asserting), _primary_term=DocValuesFormat(name=Asserting), _version=DocValuesFormat(name=Lucene90)}, maxPointsInLeafNode=1359, maxMBSortInHeap=6.490200868558901, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=is-IS, timezone=Kwajalein
  2> NOTE: Linux 5.4.204-124.362.amzn2int.x86_64 amd64/Eclipse Adoptium 17.0.3 (64-bit)/cpus=8,threads=1,free=241997352,total=536870912
  2> NOTE: All tests run in this JVM: [AsynchronousSearchQueryIT, AsynchronousSearchRejectionIT, AsynchronousSearchStatsIT]

75 tests completed, 1 failed

=== Standard output of node `node{::integTest-0}` ===

=== Standard error of node `node{::integTest-0}` ===

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest'.
> There were failing tests. See the report at: file:///tmp/tmp4wx1o2at/asynchronous-search/build/reports/tests/integTest/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 54s
```

**Comment by peterzhuamazon** [comment]
This is an existing issue where the test is flaky - https://github.com/opensearch-project/asynchronous-search/issues/105
