### ISSUE TITLE
[BUG] Security enabled integration tests are failing

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/asynchronous-search#25]
**Describe the bug**
While running integration tests with security plugin enabled, the CI is failing with error 
https://github.com/opensearch-project/asynchronous-search/pull/21/checks?check_run_id=3008459503

> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.search.asynchronous.restIT.AsynchronousSearchRestIT.testSubmitWithRetainedResponse" -Dtests.seed=32319D298A3961CE -Dtests.security.manager=false -Dtests.locale=pl -Dtests.timezone=SystemV/YST9YDT -Druntime.java=14
    javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:887)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:296)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:283)
        at org.opensearch.test.rest.OpenSearchRestTestCase.initClient(OpenSearchRestTestCase.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Other plugins installed**
Security plugin is installed in docker pull and run step in CI workflow

**To Reproduce**
1. Go to https://github.com/opensearch-project/asynchronous-search/pull/21/checks?check_run_id=3008459503
2. Re-run github action **Test and Build Workflow.**

**Expected behavior**
Integ tests pass

**Comment by saratvemulapalli** [comment]
I see it say the certificate path is missing. 
The docker image you consume should already have these configurations setup. You dont need to manually configure it again.
So can you do this:
1. Do the same CI, but manually on your machine (not on github workflow) step by step.
2. There are other plugins like Alerting and AD which run using security. 
3. ISM: Doesn't use docker, so they manually configure settings Ref: https://github.com/opensearch-project/index-management/blob/c26dbf91b348e7d538e43cbcc717aaaba099a184/build.gradle#L211
CI: https://github.com/opensearch-project/index-management/blob/main/.github/workflows/test-and-build-workflow.yml#L66
4. AD: Uses docker, so they literally dont do any configuration and rely on docker to take care of things. 
Ref: https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L183 
CI: https://github.com/opensearch-project/anomaly-detection/blob/main/.github/workflows/CI.yml#L90

**Comment by eirsep** [comment]
https://github.com/opensearch-project/asynchronous-search/pull/21/commits/f969d983b1eb7dbf27cc889875f2fdf38442fff3

The buildClient() method which adds the necessary security plugin related certs was being overridden. Removing that solved this issue.
